name: .Net

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Source/ModelTests/ModelTests.csproj
    - name: Build
      run: dotnet build --no-restore -—Å Release Source/ModelTests/ModelTests.csproj
    - name: Exploration
      run: ls Source/ModelTests/bin/
    - name: Test
      run: dotnet test --verbosity normal Source/ModelTests/bin/Release/netcoreapp3.1/ModelTests.dll
