name: .Net

on: [push, pull_request]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Heroku
        run: docker login -u=_ -p=${{ secrets.HEROKU_API_KEY }} registry.heroku.com

      - name: Build image
        run: docker build -f WebAPI.dockerfile -t registry.heroku.com/whippingboy/web .

      - name: Push Image
        run: docker push registry.heroku.com/whippingboy/web