name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy Solution
    runs-on: ubuntu-latest

    env: 
      registery: cr.yandex/crp50j9hporsn9435fmm
      app_name: YandexToday

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Deploy on Yandex.Cloud Container
        run: | 
          echo '${{ secrets.IAM }}' | docker login -u iam --password-stdin cr.yandex
          docker build . -t ${{ env.registry }}/${{ env.app_name }}
          docker push ${{ env.registry }}/${{ env.app_name }}
